// <auto-generated />
using System;
using ControleDeFrotaWebApi.Models.infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleDeFrotaWebApi.Migrations
{
    [DbContext(typeof(ControleFrotaContext))]
    [Migration("20220418000124_CriacaoDoBanco")]
    partial class CriacaoDoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleDeFrotaWebApi.Models.Domain.Entities.Motorista", b =>
                {
                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnName("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnName("cnh")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("ValidadeCNH")
                        .HasColumnName("validadeCNH")
                        .HasColumnType("datetime");

                    b.HasKey("MotoristaId");

                    b.ToTable("tbl_motor");
                });

            modelBuilder.Entity("ControleDeFrotaWebApi.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("MotoristaId", "VeiculoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("tbl_motr_veicl");
                });

            modelBuilder.Entity("ControleDeFrotaWebApi.Models.Domain.Entities.Veiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ano")
                        .HasColumnName("ano")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa")
                        .HasColumnName("placa")
                        .HasColumnType("varchar(20)");

                    b.HasKey("VeiculoId");

                    b.ToTable("tbl_veicl");
                });

            modelBuilder.Entity("ControleDeFrotaWebApi.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.HasOne("ControleDeFrotaWebApi.Models.Domain.Entities.Motorista", "Motorista")
                        .WithMany("Veiculos")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleDeFrotaWebApi.Models.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Motoristas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
